- name: Add elogind to boot
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "rc-update add elogind boot"

- name: Emerge xorg-server
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "emerge x11-base/xorg-server"

- name: Put xinitrc
  ansible.builtin.template:
    src: xinitrc.j2
    dest: /mnt/gentoo/home/{{ user.name }}/.xinitrc
