- name: Start the configuration!
  hosts: all
  gather_facts: true
  become: true
  roles:
    - name: disks
    - name: stage3
    - name: basesystem
    - name: kernel
    - name: confsystem
    - name: bootloader
    - name: finalizing

      # configuring

    - name: configuring/X
    - name: configuring/aria2
    - name: configuring/bash
    - name: configuring/bashtop
    - name: configuring/bluetooth
    - name: configuring/discord
    - name: configuring/dmenu
    - name: configuring/dwm
    - name: configuring/feh
    - name: configuring/firefox
    - name: configuring/fuse
    - name: configuring/git
    - name: configuring/hwinfo
    - name: configuring/neofetch
    - name: configuring/neovim
    - name: configuring/p7zip
    - name: configuring/signal
    - name: configuring/slstatus
    - name: configuring/sound
    - name: configuring/st
    - name: configuring/sudo
    - name: configuring/unrar
    - name: configuring/unzip
    - name: configuring/wifi
    - name: configuring/xcompmgr

