- name: Emerge GRUB
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "emerge sys-boot/grub"

- name: Install GRUB BIOS
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "grub-install {{ storage.install }}"
  when: compiling_options.efi_grub is false 

- name: Install GRUB EFI
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "grub-install --target=x86_64-efi --efi-directory=/boot"
  when: compiling_options.efi_grub is true  

- name: Configure
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "grub-mkconfig -o /boot/grub/grub.cfg"
