- name: Make sure mountpoint exists
  ansible.builtin.file:
    path: /mnt/gentoo
    state: directory

- name: Mounting {{ storage.partitions.root.name }} partition
  ansible.posix.mount:
    path: /mnt/gentoo
    state: mounted
    src: "{{ storage.install }}{{ storage.partitions.root.number }}"
    fstype: "{{ storage.partitions.root.filesystem }}"
  when: '"nvme" not in storage.install'

- name: Mounting {{ storage.partitions.root.name }} partition
  ansible.posix.mount:
    path: /mnt/gentoo
    state: mounted
    src: "{{ storage.install }}p{{ storage.partitions.root.number }}"
    fstype: "{{ storage.partitions.root.filesystem }}"
  when: '"nvme" in storage.install'
