- name: Make package.use apps directory
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/package.use/apps
    state: directory

- name: Unmask
  ansible.builtin.template:
    src: firefox.j2
    dest: /mnt/gentoo/etc/portage/package.use/apps/firefox

- name: Emerge
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "emerge www-client/firefox"
