#
# system install
#

user:
  name: mimi07 # user name for the system user
  password: this+is-a+strong_one # your system password
  groups: users,wheel,audio,video # groups for the previously defined user

storage:
  install: /dev/nvme0n1 # install drive name
  label: gpt # gpt / msdos
  partitions:
    boot:
      name: boot
      number: 1
      size: 256 # MiB
      filesystem: vfat
    swap:
      name: swap
      number: 2
      size: 8192 # MiB
      filesystem: swap
    root: 
      name: root
      number: 3
      size: 100 # 100% (the rest of the drive)
      filesystem: ext4

compiling_options:
  common_flags: -march=native -O2 -pipe
  makeopts: 6
  efi_grub: true
  use_flags: wayland X xwayland elogind bluetooth pulseaudio screencast -systemd
  video_cards: intel
  mirrors: http://gentoo.mirrors.ovh.net/gentoo-distfiles/

portage_options:
  profile: 1

timezone: Europe/Bucharest

locale: | 
  en_US ISO-8859-1 
  en_US.UTF-8 UTF-8
locale_set: en_US.utf8

kernel: manual # manual

hostname: gentoo

hosts: |
  example.com           example

#
# system configuration (after reboot)
#

wifi:
  ssid: "example.name"
  password: "example.password"
