- name: Create package.license directory
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/package.license
    state: directory

- name: Create the kernel license file
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/package.license/kernel
    state: touch

- name: Accept the linux firmware license
  ansible.builtin.template:
    src: kernel.j2
    dest: /mnt/gentoo/etc/portage/package.license/kernel

- name: Installing linux firmware
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "emerge sys-kernel/linux-firmware"
