- name: Mounting the boot partition
  ansible.posix.mount:
    path: /mnt/gentoo/boot
    state: mounted
    src: "{{ storage.install }}{{ storage.partitions.boot.number }}"
    fstype: vfat
  when: '"nvme" not in storage.install'

- name: Mounting the boot partition
  ansible.posix.mount:
    path: /mnt/gentoo/boot
    state: mounted
    src: "{{ storage.install }}p{{ storage.partitions.boot.number }}"
    fstype: vfat
  when: '"nvme" in storage.install'
