- name: Make unmask directory
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/package.accept_keywords/apps
    state: directory

- name: Unmask
  ansible.builtin.template:
    src: bashtop.j2
    dest: /mnt/gentoo/etc/portage/package.accept_keywords/apps/bashtop

- name: Emerge
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "emerge sys-process/bashtop"
  
