- name: Make package.use suckless folder
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/package.use/suckless
    state: directory

- name: Place dmenu savedconfig
  ansible.builtin.template:
    src: dmenu.j2
    dest: /mnt/gentoo/etc/portage/package.use/suckless/dmenu

- name: Get dmenu version
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo/ sh -c "emerge -pv x11-misc/dmenu | grep -m1 'x11-misc/dmenu-' | awk {' print \$4 '} | sed s/::gentoo// | sed s/x11-misc\\\///"
  register: dmenuver

- name: Make x11-misc directory
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/savedconfig/x11-misc
    state: directory

- name: Put {{ dmenuver.stdout }} file
  ansible.builtin.template:
    src: dmenu-config.j2
    dest: "/mnt/gentoo/etc/portage/savedconfig/x11-misc/{{ dmenuver.stdout }}"

- name: Emerge to apply config 
  ansible.builtin.shell:
    cmd: chroot /mnt/gentoo sh -c "emerge x11-misc/dmenu"

